apiVersion: v1
kind: Service
metadata:
  labels:
    run: blue
  name: new-blue-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 32711
  selector:
    run: blue
  type: NodePort
status:
  loadBalancer: {}
