apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-inventory-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-inventory-db
  template:
    metadata:
      labels:
        app: user-inventory-db
    spec:
      containers:
        - name: postgres
          image: arupdeb381/user-invtry-db:1.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: inventory
            - name: POSTGRES_USER
              value: inventory
            - name: POSTGRES_PASSWORD
              value: inventory123
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
