apiVersion: v1
kind: Pod
metadata:
  labels:
    run: red
  name: red
  namespace: my-first-ns
spec:
  containers:
  - image: nginx
    name: red
    resources:
      requests:
        cpu: "500m"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "512Mi"
