name: Hello World Workflow
on: workflow_dispatch
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: |
          echo "Hello 01"
          echo "Hello 02"
          echo "Hello 03"
        
